# Site settings
title: Aditya Blog
SEOTitle: AD Blog | Aditya Blog
header-img: img/home-bg.jpg
email: Mr.adityasaritasingh@gmail.com
description: "Software Engineer, Product Manager, Quizzer, DIY enthusiast, and Hacker"
keyword: "Product Management, Product Designer, Machine Learning, Computer Vision, Quiz"
url: "https://adigeak.github.io" # Your host, for absolute URL
baseurl: "" # For example, '/blog' if your blog is hosted on 'host/blog'

# Publish posts or collection documents with a future date
future: true

# SNS settings
RSS: true # Enable RSS feed
github_username: adigeak
twitter_username: 01100001ditya
linkedin_username: adigeak # Add LinkedIn username

# Build settings
highlighter: rouge # Use Rouge for code highlighting
permalink: pretty
paginate: 5 # Number of posts per page
exclude:
    - less
    - node_modules
    - Gruntfile.js
    - package.json
    - README.md
    - README.zh.md
anchorjs: true # Enable Anchor.js for headers

# Timezone settings
timezone: Asia/Kolkata # Set timezone

# Plugins
plugins:
    - jekyll-paginate

# Markdown settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter_opts:
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

# Disqus settings
# disqus_username: aditya_blog # Add Disqus username

# Netease settings
netease_comment: false

# Analytics settings
# google_analytics: UA-12345678-1 # Add your Google Analytics ID

# Sidebar settings
sidebar: true
sidebar-about-description: "Product Manager, Quizzer, Hobbyist <br> An AI/ML developer & designer who accidentally fell in love with electronics and product design."
sidebar-avatar: /img/avatar-ad.png

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Friends (Optional)
friends:
    - title: "Aditya's GitHub"
      href: "https://github.com/adigeak"
    - title: "Aditya's LinkedIn"
      href: "https://www.linkedin.com/in/adigeak/"

# Add the collections section here
collections:
    portfolio:
        output: true
